services:
  - type: web
    name: backend
    env: docker
    repo: https://github.com/ru-se/Meelette
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: GOOGLE_MAPS_API_KEY
        value: your_google_maps_api_key
    autoDeploy: true
    plan: free

  - type: web
    name: frontend
    env: docker
    repo: https://github.com/ru-se/Meelette
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://backend.onrender.com  # バックエンドのURL
    autoDeploy: true
    plan: free
