services:
  - name: backend
    type: web
    env: docker
    plan: free  # 必要に応じてプランを変更
    dockerfilePath: ./backend/Dockerfile  # Dockerfileのパス
    buildCommand: docker build -t backend ./backend  # ビルドコマンド
    startCommand: docker run -p 8000:8000 backend  # 起動コマンド
    envVars:
      - key: NODE_ENV
        value: production  # 環境変数の設定
    volumes:
      - volumeName: backend-data  # バックエンド用のデータボリューム
    restartPolicy: always  # サービスの再起動ポリシー

  - name: frontend
    type: web
    env: docker
    plan: free  # 必要に応じてプランを変更
    dockerfilePath: ./frontend/Dockerfile  # Dockerfileのパス
    buildCommand: docker build -t frontend ./frontend  # ビルドコマンド
    startCommand: docker run -p 80:80 frontend  # 起動コマンド
    envVars:
      - key: NODE_ENV
        value: production  # 環境変数の設定
    dependsOn:
      - backend  # バックエンドが起動するまで待機
    volumes:
      - volumeName: frontend-data  # フロントエンド用のデータボリューム
    extraHosts:
      - name: backend
        value: host.docker.internal  # バックエンドへのホスト名設定
    restartPolicy: always  # サービスの再起動ポリシー

volumes:
  - name: backend-data
  - name: frontend-data
